version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend-core
    env_file:
      - frontend/.env
  backend-core:
    build:
      context: ./backend-core
    ports:
      - 8080:8080
    volumes:
      - ./backend-core:/app
    env_file:
      - backend-core/.env
    depends_on:
      - db-core
  db-core:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "boards"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 10s
      retries: 5
