version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend-core
    env_file:
      - frontend/.env
  backend-core:
    container_name: backend-core
    build:
      context: ./backend-core
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - ./backend-core:/app/src
    env_file:
      - backend-core/.env
    environment:
      - DOCKER=true
    depends_on:
      - db-core
  db-core:
    container_name: db-core
    build:
      context: ./db-core
    restart: always
    env_file:
      - db-core/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - db-core-data:/var/lib/postgresql/data
  swagger-core:
    container_name: swagger-core
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: "/spec/swagger.yaml"
    volumes:
      - ./backend-core/swagger.yaml:/spec/swagger.yaml
    ports:
      - 8081:8080
volumes:
  db-core-data:
