version: "3"

services:
  app:
    build:
      context: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    depends_on:
      - server
    env_file:
      - app/.env
  server:
    build:
      context: ./server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    env_file:
      - server/.env