apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  ENV: production
  BACKEND_URL: http://backend-core:80
  # TODO: NEXT_PUBLIC_BACKEND_URL to be changed to loadbalancer stable IP
  NEXT_PUBLIC_BACKEND_URL: http://backend-core:80