apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-core-deployment
spec:
  selector:
    matchLabels:
      app: backend-core
  template:
    metadata:
      labels:
        app: backend-core
    spec:
      containers:
        - name: backend-core
          image: wuvictor95/backend-core:1.1.1
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: backend-core-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-core-user
                  key: db-core-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-core-password
                  key: db-core-password
            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-signing-key
                  key: jwt-signing-key
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: jwt-expiration
                  key: jwt-expiration
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: amqp-password
                  key: amqp-password

