apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-core-deployment
spec:
  selector:
    matchLabels:
      app: db-core
  template:
    metadata:
      labels:
        app: db-core
    spec:
      containers:
        - name: db-core
          image: postgres
          volumeMounts:
            - name: db-core-persistent-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: boards
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-core-user
                  key: db-core-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-core-password
                  key: db-core-password
      volumes:
        - name: db-core-persistent-storage
          persistentVolumeClaim:
            claimName: db-core-pvc