apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend-port
      port: 80
      targetPort: 3000
    - name: frontend-port-https
      port: 443
      targetPort: 3000
  type: LoadBalancer
